# Generated by Django 5.2.6 on 2025-10-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0002_alter_category_options_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
