# Generated by Django 5.2.6 on 2025-10-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0003_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=50)),
                ('prediction', models.TextField()),
            ],
        ),
    ]
