# Generated by Django 5.2.6 on 2025-10-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0004_horoscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='horoscope_images/'),
        ),
    ]
